#!/bin/sh
# Refreshes tests/corpus/ from real published flix.toml manifests on GitHub.
#
#   sh tests/fetch-corpus.sh
#
# This is a maintenance tool, not a test. It is not run by lint, by tests/run.sh, or by
# CI: it needs the network, the `gh` CLI and python3. What it produces is committed, so
# the corpus test itself stays offline, deterministic, and fast.
#
# Two things are written per refresh:
#
#   tests/corpus/*.toml           verbatim manifests, pinned to the commit they came from
#   tests/corpus/expected.tsv     what a conforming TOML parser reads from each one
#   tests/corpus/PROVENANCE.tsv   where each file came from, so the fetch is reproducible
#
# expected.tsv is the point. It is generated by python3's tomllib -- a conforming parser
# flixw's hand-written scanner is then required to agree with, file by file. Recording
# the oracle's answer at fetch time is what keeps the comparison honest without making
# python3 a dependency of the suite.
set -eu

# shellcheck disable=SC1007  # CDPATH is cleared for this command only; see src/flixw
root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd -P)
corpus=$root/tests/corpus
limit=${FLIXW_CORPUS_LIMIT:-100}

for tool in gh python3 curl; do
  if ! command -v "$tool" >/dev/null 2>&1; then
    echo "fetch-corpus: $tool is required" >&2
    exit 1
  fi
done

work=$root/tests/.work/corpus
rm -rf "$work"
mkdir -p "$work"

echo "searching GitHub for flix.toml ..."
gh search code --filename flix.toml --limit "$limit" \
   --json repository,path,url > "$work/hits.json"

# The search matches on filename substrings, so Netflix.toml and omniflix.toml.j2 come
# back too. Only an exact basename is a Flix manifest. Downloads are pinned to the commit
# the search returned, so a refresh is reproducible from the provenance table alone.
python3 - "$work" "$corpus" <<'PY'
import hashlib, json, pathlib, subprocess, sys, tomllib

work, corpus = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2])
hits = json.loads((work / "hits.json").read_text())

seen, rows, prov, skipped = {}, [], [], []
for h in hits:
    path = h["path"]
    if pathlib.PurePosixPath(path).name != "flix.toml":
        continue
    repo = h["repository"]["nameWithOwner"]
    # .../OWNER/REPO/blob/SHA/PATH -> raw.githubusercontent.com/OWNER/REPO/SHA/PATH
    parts = h["url"].split("/blob/", 1)
    if len(parts) != 2:
        continue
    sha, _, rel = parts[1].partition("/")
    raw = f"https://raw.githubusercontent.com/{repo}/{sha}/{rel}"
    got = subprocess.run(["curl", "-fsSL", raw], capture_output=True)
    if got.returncode != 0:
        skipped.append((repo, path, "download failed"))
        continue
    text = got.stdout.decode("utf-8", "replace")

    # Distinct shapes are what exercise a scanner; a hundred copies of the same five
    # lines exercise it once. Deduplicate on content and keep the first source seen.
    digest = hashlib.sha256(text.encode("utf-8")).hexdigest()
    if digest in seen:
        continue

    # A file a conforming parser cannot read is not evidence about flixw's scanner:
    # there is no ground truth to compare against. Record why it was dropped.
    try:
        doc = tomllib.loads(text)
    except tomllib.TOMLDecodeError as e:
        skipped.append((repo, path, f"not valid TOML: {e}"))
        continue

    slug = (repo.replace("/", "__") + "__" + rel.replace("/", "__"))[:-5]
    seen[digest] = slug
    (corpus / f"{slug}.toml").write_text(text, encoding="utf-8")
    prov.append((slug, repo, rel, sha))

    flix = doc.get("package", {}).get("flix") if isinstance(doc.get("package"), dict) else None
    if isinstance(flix, str):
        rows.append((slug, "OK", flix))
    elif flix is None:
        rows.append((slug, "NONE", ""))
    else:
        rows.append((slug, "NONSTRING", type(flix).__name__))
    print(f"  {slug}")

for stale in corpus.glob("*.toml"):
    if stale.stem not in seen.values():
        stale.unlink()

(corpus / "expected.tsv").write_text(
    "# generated by tests/fetch-corpus.sh -- oracle: python3 tomllib\n"
    "# <file>\t<OK|NONE|NONSTRING>\t<value>\n"
    + "".join(f"{s}\t{k}\t{v}\n" for s, k, v in sorted(rows)),
    encoding="utf-8")

(corpus / "PROVENANCE.tsv").write_text(
    "# generated by tests/fetch-corpus.sh -- every file here is someone else's work,\n"
    "# copied verbatim and unmodified from a public repository at the commit named.\n"
    "# <file>\t<repository>\t<path>\t<commit>\n"
    + "".join(f"{s}\t{r}\t{p}\t{c}\n" for s, r, p, c in sorted(prov)),
    encoding="utf-8")

print(f"\n{len(rows)} distinct manifests, {len(skipped)} skipped")
for repo, path, why in skipped:
    print(f"  skip {repo}/{path}: {why}")
PY

echo
echo "corpus refreshed in $corpus"
echo "review the diff, then run: sh tests/run.sh"
