#!/bin/sh
# Builds the release payload into <output-dir>:
#
#   flixw-<version>.tar.gz    the wrapper files, over a project root
#   flixw-<version>.zip       the same, for a machine without tar
#   flixw.java                stage 0 on its own, for the `java flixw.java wrapper --install` route
#   flixw-install.java        the installer, fetched on first use and cached
#   flixw-completion.java     the TAB-completion generator, fetched on first use and cached
#   flixw-jdk.java            the optional JDK provisioner, fetched on first use and cached
#   SHA256SUMS                digests of all of the above
#
# The archives are not assembled by hand. `install` is run into a staging directory and
# whatever it wrote is what gets packed, so the archive route and the install route cannot
# diverge -- an archive built from a hand-written file list would have to repeat install's
# rules about CRLF and the executable bit, and would silently stop matching the day one of
# them changed. tests/run.sh proves the two are identical by extracting and diffing.
#
# This is a maintenance and release tool rather than a test. CI calls it on a tag; run it
# by hand to reproduce a published digest.
set -eu

out=${1:-}
if [ -z "$out" ]; then
  echo "usage: sh tests/pack.sh <output-dir>" >&2
  exit 2
fi
# shellcheck disable=SC1007  # CDPATH is cleared for these commands only; see src/flixw
root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
mkdir -p "$out"
# shellcheck disable=SC1007
out=$(CDPATH= cd -- "$out" && pwd)

for tool in java zip; do
  command -v "$tool" >/dev/null 2>&1 || { echo "pack: $tool is required" >&2; exit 2; }
done
if command -v sha256sum >/dev/null 2>&1; then sum() { sha256sum "$@"; }
elif command -v shasum >/dev/null 2>&1;  then sum() { shasum -a 256 "$@"; }
else echo "pack: no sha256sum or shasum" >&2; exit 2
fi

version=$(java "$root/src/flixw.java" wrapper --version | head -1 | cut -d' ' -f2)
case $version in
  [0-9]*.[0-9]*.[0-9]*) ;;
  *) echo "pack: could not read the wrapper version (got '$version')" >&2; exit 1 ;;
esac

stage=$(mktemp -d)
work=$(mktemp -d)
trap 'rm -rf "$stage" "$work"' EXIT INT TERM
# The shim text lives in the installer asset now, so the staging install is pointed at the
# release being built rather than at the network. This is also the only honest way to build
# it: the asset a release ships must be the one that wrote that release's archives.
fixture=$work/release
mkdir -p "$fixture"
cp "$root/src/flixw.java" "$root/src/flixw-completion.java" \
   "$root/src/flixw-jdk.java" "$root/src/flixw-install.java" "$fixture/"
(cd "$fixture" && sum flixw.java flixw-completion.java flixw-jdk.java flixw-install.java \
   > SHA256SUMS)
FLIXW_ASSET_SOURCE="file://$fixture/" FLIX_CACHE_HOME="$work/cache" \
  java "$root/src/flixw.java" wrapper --install "$stage" >/dev/null

# What ships is the documented source with its commentary removed. Every adopting project
# commits .flixw/flixw.java into its own repository, and a third of that file is prose
# written for whoever audits flixw itself -- an audience that reads the website or the
# repository, both named in the header the stripper writes.
#
# Generated here rather than committed, and generated by a pure function, because the
# readable artifact and the running one are now different files. That is only honest while
# anyone can regenerate the second from the first: `java tests/strip.java src/flixw.java
# <version>` at the tag reproduces these bytes exactly, which tests/lint.sh checks.
shipped=$work/flixw.java
java "$root/tests/strip.java" "$root/src/flixw.java" "$version" > "$shipped"
# It has to be the same program, and the cheapest proof that it still compiles is to
# compile it. A release that shipped a stripped file javac rejects would be unrunnable in
# every project that received it.
javac -d "$work/shipped-classes" "$shipped" || {
  echo "pack: the stripped stage 0 does not compile" >&2; exit 1; }
cp "$shipped" "$stage/.flixw/flixw.java"

# .gitattributes is deliberately not packed. install *merges* its block into whatever the
# project already has; an archive can only overwrite, and clobbering a project's own
# attributes to pin our four line endings is a bad trade. `./flixw doctor --fix` merges it
# after extraction, and `./flixw validate` says so if it was skipped.
rm -f "$stage/.gitattributes"

#
# Timestamps are normalised so that repacking the same commit yields the same bytes, and a
# published digest can be reproduced rather than merely trusted. zip stores DOS times,
# whose epoch is 1980; tar and gzip are given a real zero.
TZ=UTC find "$stage" -exec touch -t 198001010000 {} +

tar_flags=''
if tar --version 2>/dev/null | head -1 | grep -q GNU; then
  # Only GNU tar can pin member order and ownership. Elsewhere the archive is correct but
  # not bit-reproducible, which is why the release job runs on Linux.
  tar_flags='--sort=name --owner=0 --group=0 --numeric-owner --mtime=@0'
fi
# shellcheck disable=SC2086  # word splitting is the point; the flags are ours
(cd "$stage" && tar $tar_flags -cf - flixw flixw.cmd .flixw) \
  | gzip -9 -n > "$out/flixw-$version.tar.gz"

rm -f "$out/flixw-$version.zip"
# -X drops uid/gid and the extra timestamp fields, which are per-machine noise; the unix
# permission bits that carry the executable flag are not extra fields and survive it.
# TZ=UTC again: zip stores wall-clock local time, so the same tree packed in Berlin and in
# UTC would otherwise differ in four bytes per member.
(cd "$stage" && TZ=UTC zip -qrX "$out/flixw-$version.zip" flixw flixw.cmd .flixw)

cp "$shipped" "$out/flixw.java"
# No flix.java. Releases up to 0.19.1 published stage 0 under that name and their upgrade
# asks for it by name, so this used to be a second copy of stage 0 in every release. The
# rename shipped in 0.20.0 a week after the first release and nothing adopted the wrapper
# before it, so the bridge served nobody; the installer's matching rename migration went
# with it.

# Not packed into the archives: neither is ever installed into a project. Both are fetched
# on first use and cached machine-wide -- ensureAsset in src/flixw.java expects them as
# bare release assets beside flixw.java, not inside a tarball. flixw-jdk.java is reached by
# `wrapper --install-jdk`, flixw-completion.java by `wrapper --completion <shell>`.
cp "$root/src/flixw-completion.java" "$out/flixw-completion.java"
cp "$root/src/flixw-jdk.java" "$out/flixw-jdk.java"
cp "$root/src/flixw-install.java" "$out/flixw-install.java"

(cd "$out" && sum "flixw-$version.tar.gz" "flixw-$version.zip" flixw.java \
              flixw-completion.java flixw-jdk.java flixw-install.java > SHA256SUMS)
echo "packed flixw $version into $out"
cat "$out/SHA256SUMS"
