#!/bin/sh
# Builds the release payload into <output-dir>:
#
#   flixw-<version>.tar.gz    the wrapper files, over a project root
#   flixw-<version>.zip       the same, for a machine without tar
#   flixw.java                stage 0 on its own, for the `java flixw.java wrapper --install` route
#   flixw-setup.java        the installer, fetched on first use and cached
#   flixw-jdk.java            the optional JDK provisioner, fetched on first use and cached
#   SHA256SUMS                digests of all of the above
#
# The archives are not assembled by hand. `install` is run into a staging directory and
# whatever it wrote is what gets packed, so the archive route and the install route cannot
# diverge -- an archive built from a hand-written file list would have to repeat install's
# rules about CRLF and the executable bit, and would silently stop matching the day one of
# them changed. tests/run.sh proves the two are identical by extracting and diffing.
#
# This is a maintenance and release tool rather than a test. CI calls it on a tag; run it
# by hand to reproduce a published digest.
set -eu

out=${1:-}
if [ -z "$out" ]; then
  echo "usage: sh tests/pack.sh <output-dir>" >&2
  exit 2
fi
# shellcheck disable=SC1007  # CDPATH is cleared for these commands only; see src/stage0/flixw
root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
mkdir -p "$out"
# shellcheck disable=SC1007
out=$(CDPATH= cd -- "$out" && pwd)

for tool in java zip; do
  command -v "$tool" >/dev/null 2>&1 || { echo "pack: $tool is required" >&2; exit 2; }
done
if command -v sha256sum >/dev/null 2>&1; then sum() { sha256sum "$@"; }
elif command -v shasum >/dev/null 2>&1;  then sum() { shasum -a 256 "$@"; }
else echo "pack: no sha256sum or shasum" >&2; exit 2
fi

version=$(java "$root/src/stage0/flixw.java" wrapper --version | head -1 | cut -d' ' -f2)
case $version in
  [0-9]*.[0-9]*.[0-9]*) ;;
  *) echo "pack: could not read the wrapper version (got '$version')" >&2; exit 1 ;;
esac

stage=$(mktemp -d)
work=$(mktemp -d)
trap 'rm -rf "$stage" "$work"' EXIT INT TERM
# The shim text lives in the installer asset now, so the staging install is pointed at the
# release being built rather than at the network. This is also the only honest way to build
# it: the asset a release ships must be the one that wrote that release's archives.
fixture=$work/release
mkdir -p "$fixture"
cp "$root/src/stage0/flixw.java" \
   "$root/src/assets/flixw-jdk.java" "$root/src/assets/flixw-setup.java" \
   "$root/src/assets/flixw-inspect.java" "$root/src/assets/flixw-help.java" \
   "$root/src/assets/flixw-examples.java" "$fixture/"
# Unstripped here on purpose: this fixture exists only so the staging install can run
# offline, and the stage 0 it writes is replaced by $shipped a few lines below.
(cd "$fixture" && sum flixw.java flixw-jdk.java flixw-setup.java \
   flixw-inspect.java flixw-help.java flixw-examples.java \
   > SHA256SUMS)
FLIXW_ASSET_SOURCE="file://$fixture/" FLIX_CACHE_HOME="$work/cache" \
  java "$root/src/assets/flixw-setup.java" setup "$stage" "$root/src/stage0/flixw.java" >/dev/null

# What ships is the documented source with its commentary removed. Every adopting project
# commits .flixw/flixw.java into its own repository, and a third of that file is prose
# written for whoever audits flixw itself -- an audience that reads the website or the
# repository, both named in the header the stripper writes.
#
# Generated here rather than committed, and generated by a pure function, because the
# readable artifact and the running one are now different files. That is only honest while
# anyone can regenerate the second from the first: `java tests/strip.java src/stage0/flixw.java
# <version>` at the tag reproduces these bytes exactly, which tests/lint.sh checks.
shipped=$work/flixw.java
java "$root/tests/strip.java" "$root/src/stage0/flixw.java" "$version" "stage 0" > "$shipped"
# It has to be the same program, and the cheapest proof that it still compiles is to
# compile it. A release that shipped a stripped file javac rejects would be unrunnable in
# every project that received it.
javac -d "$work/shipped-classes" "$shipped" || {
  echo "pack: the stripped stage 0 does not compile" >&2; exit 1; }
cp "$shipped" "$stage/.flixw/flixw.java"

# .gitattributes is deliberately not packed. install *merges* its block into whatever the
# project already has; an archive can only overwrite, and clobbering a project's own
# attributes to pin our four line endings is a bad trade. `./flixw doctor --fix` merges it
# after extraction, and `./flixw validate` says so if it was skipped.
rm -f "$stage/.gitattributes"

#
# Timestamps are normalised so that repacking the same commit yields the same bytes, and a
# published digest can be reproduced rather than merely trusted. zip stores DOS times,
# whose epoch is 1980; tar and gzip are given a real zero.
TZ=UTC find "$stage" -exec touch -t 198001010000 {} +

tar_flags=''
if tar --version 2>/dev/null | head -1 | grep -q GNU; then
  # Only GNU tar can pin member order and ownership. Elsewhere the archive is correct but
  # not bit-reproducible, which is why the release job runs on Linux.
  tar_flags='--sort=name --owner=0 --group=0 --numeric-owner --mtime=@0'
fi
# shellcheck disable=SC2086  # word splitting is the point; the flags are ours
(cd "$stage" && tar $tar_flags -cf - flixw flixw.cmd .flixw) \
  | gzip -9 -n > "$out/flixw-$version.tar.gz"

rm -f "$out/flixw-$version.zip"
# -X drops uid/gid and the extra timestamp fields, which are per-machine noise; the unix
# permission bits that carry the executable flag are not extra fields and survive it.
# TZ=UTC again: zip stores wall-clock local time, so the same tree packed in Berlin and in
# UTC would otherwise differ in four bytes per member.
(cd "$stage" && TZ=UTC zip -qrX "$out/flixw-$version.zip" flixw flixw.cmd .flixw)

cp "$shipped" "$out/flixw.java"
# No flix.java. Releases up to 0.19.1 published stage 0 under that name and their upgrade
# asks for it by name, so this used to be a second copy of stage 0 in every release. The
# rename shipped in 0.20.0 a week after the first release and nothing adopted the wrapper
# before it, so the bridge served nobody; the installer's matching rename migration went
# with it.

# Not packed into the archives: neither is ever installed into a project. Both are fetched
# on first use and cached machine-wide -- ensureAsset in src/stage0/flixw.java expects them as
# bare release assets beside flixw.java, not inside a tarball. flixw-jdk.java is reached by
# `wrapper --install-jdk`, flixw-help.java by `help` and `completion <shell>`.
# Stripped too, for the same reason stage 0 is: the commentary is written for whoever
# audits flixw, and that reader is in the repository or on the site -- both named in the
# header the stripper leaves behind. Compiled after stripping, because a release shipping
# one javac rejects would break whichever command needs it, and only at that point.
# picocli, republished as a release asset so the renderer's dependency rides the same
# SHA256SUMS, the same FLIXW_ASSET_SOURCE mirror and the same purge as everything else.
# Fetching it from Maven Central at run time would have been a second trust story for a
# wrapper whose whole claim is that there is only one. Apache-2.0; redistribution is fine.
# The digest lives here rather than in stage 0 because it is a *release-time* claim: at
# run time picocli is verified against the release's own SHA256SUMS like every other asset,
# so a constant in stage 0 would be dead weight on every invocation. Pinning it here is what
# stops a silently re-uploaded artifact from being republished under a flixw tag, and keeps
# `pack.sh` reproducible for anyone rebuilding a release from the same source.
pv=$(sed -n 's/.*PICOCLI_VERSION = "\([^"]*\)".*/\1/p' "$root/src/stage0/flixw.java")
PICOCLI_SHA256=f86e30fffd10d2b13b8caa8d4b237a7ee61f2ffccf5b1941de718b765d235bf8
curl -fsSL -o "$out/picocli-$pv.jar" \
  "https://repo1.maven.org/maven2/info/picocli/picocli/$pv/picocli-$pv.jar" || {
  echo "pack: cannot fetch picocli $pv" >&2; exit 1; }
got=$(sum "$out/picocli-$pv.jar" | cut -d' ' -f1)
[ "$got" = "$PICOCLI_SHA256" ] || {
  echo "pack: picocli $pv digest mismatch: pinned $PICOCLI_SHA256, served $got" >&2; exit 1; }

for a in jdk inspect setup help examples; do
  java "$root/tests/strip.java" "$root/src/assets/flixw-$a.java" "$version" "flixw-$a.java" \
    > "$out/flixw-$a.java"
  # flixw-help.java is the one asset with a compile-time dependency, and it is the jar this
  # same release publishes -- so compiling against it here also proves the two agree.
  javac -cp "$out/picocli-$pv.jar" -d "$work/asset-classes" "$out/flixw-$a.java" || {
    echo "pack: the stripped flixw-$a.java does not compile" >&2; exit 1; }
done

# Published, because the file itself claims the release publishes it -- and because a
# licence and provenance claim that only exists in the source tree is not much of a claim to
# someone holding the jar. Not packed into the archives: picocli reaches a machine cache,
# never an adopting project, so a project has no third party to give notice of.
cp "$root/THIRD_PARTY_NOTICES.md" "$out/THIRD_PARTY_NOTICES.md"

(cd "$out" && sum "flixw-$version.tar.gz" "flixw-$version.zip" flixw.java \
              flixw-jdk.java flixw-setup.java flixw-inspect.java \
              flixw-help.java flixw-examples.java "picocli-$pv.jar" THIRD_PARTY_NOTICES.md \
              > SHA256SUMS)
echo "packed flixw $version into $out"
cat "$out/SHA256SUMS"
