import java.util.List;

/**
 * flixw's TAB-completion generator.  Fetched once per machine per flixw release by
 * {@code ./flixw completion <shell>}, verified against the release's own
 * {@code SHA256SUMS} the same way {@code wrapper --upgrade} verifies {@code flixw.java}
 * itself, cached, and source-launched from there on -- exactly like a {@code .java}
 * plugin: {@code java flixw-completion.java <shell> <verbs>}.
 *
 * A pure function of its two arguments: it reads no other flixw state, declares no
 * dependency on {@code WRAPPER_VERBS} or {@code BUILTIN_VERBS}, and needs none. That is
 * what lets stage 0 cache it forever once fetched -- nothing in it can go stale except by
 * a new release, exactly when the cache entry moves to a new, version-keyed path.
 */
final class flixwcompletion {
    private flixwcompletion() {}

    public static void main(String[] args) {
        if (args.length != 2) {
            System.err.println("usage: java flixw-completion.java <shell> <verbs>");
            System.exit(87);
        }
        System.out.print(render(args[0], args[1]));
    }

    /**
     * @param shell one of {@code bash}, {@code zsh}, {@code fish}, {@code pwsh}
     * @param verbsCsv the fallback verb list, comma-joined and already sorted -- the same
     *     union of {@code WRAPPER_VERBS} and {@code BUILTIN_VERBS} the caller substitutes
     *     for {@code @VERBS@} below, formatted per shell here
     * @return the script text, ending in a newline
     */
    static String render(String shell, String verbsCsv) {
        List<String> verbs = verbsCsv.isEmpty() ? List.of() : List.of(verbsCsv.split(","));
        return switch (shell) {
            case "bash" -> COMPL_BASH.replace("@VERBS@", String.join(" ", verbs));
            case "zsh" -> COMPL_ZSH.replace("@VERBS@", String.join(" ", verbs));
            case "fish" -> COMPL_FISH.replace("@VERBS@", String.join(" ", verbs));
            case "pwsh" -> COMPL_PWSH.replace("@VERBS@", quotedCsv(verbs));
            default -> throw new IllegalArgumentException("unknown shell: " + shell);
        };
    }

    /** PowerShell's {@code @(...)} array literal needs each element single-quoted. */
    private static String quotedCsv(List<String> verbs) {
        StringBuilder b = new StringBuilder();
        for (int i = 0; i < verbs.size(); i++) {
            if (i > 0) b.append(',');
            b.append('\'').append(verbs.get(i)).append('\'');
        }
        return b.toString();
    }

    static final String COMPL_BASH = """
        # flixw TAB completion for bash -- GENERATED by `flixw completion bash`.
        #
        #   ./flixw completion bash > ~/.local/share/bash-completion/completions/flixw
        #
        # Candidates are read at TAB time from <project>/.flixw/local/verbs, the note stage 0
        # leaves after it resolves a compiler, so they follow the pin and this file does not
        # have to be regenerated after `pin`.  Nothing here starts a JVM: a stage 0 launch
        # plus the digest re-hash flixw does on every run would cost more than typing the verb.

        _flixw_root() {
          # The project is wherever the wrapper being completed lives, not the working
          # directory: `../other/flixw` is a different project's verb set, and completing it
          # from this one would be confidently wrong.
          local d
          d=$(dirname -- "$1" 2>/dev/null) || d=.
          [ -n "$d" ] || d=.
          printf '%s' "$d"
        }

        _flixw() {
          local cur root note words compl script fn saved0 saved_line
          cur=${COMP_WORDS[COMP_CWORD]}
          root=$(_flixw_root "${COMP_WORDS[0]}")
          note=$root/.flixw/local/verbs

          if [ "$COMP_CWORD" -eq 1 ]; then
            # No note yet means this project has never resolved a compiler.  The baked-in
            # list is this wrapper release's own view -- stale in the same harmless way the
            # built-in verb table in stage 0 is, and better than completing nothing.
            if [ -r "$note" ]; then words=$(cat -- "$note" 2>/dev/null)
            else words="@VERBS@"; fi
            # shellcheck disable=SC2207
            COMPREPLY=( $(compgen -W "$words" -- "$cur") )
            return 0
          fi

          # Past the verb, the compiler owns the arguments.  A picocli-based Flix ships a
          # completer for them and stage 0 caches it; stock Flix is scopt and ships none, so
          # the note is absent and `-o default` falls through to filename completion.
          compl=$root/.flixw/local/completion
          [ -r "$compl" ] || return 0
          script=$(cat -- "$compl" 2>/dev/null)
          [ -n "$script" ] && [ -r "$script" ] || return 0

          # The registration line, which is the only part of a generated completer that is
          # not the generator's private business: any bash completion script must end with
          # one for the shell to use it at all.  Reading the function name from there rather
          # than assuming picocli's `_complete_<name>` spelling means a rename upstream costs
          # filename completion for one release instead of a broken completer.
          fn=$(sed -n 's/^complete .*-F \\([A-Za-z_][A-Za-z0-9_]*\\).*/\\1/p' "$script" 2>/dev/null | head -1)
          [ -n "$fn" ] || return 0
          if ! declare -F "$fn" >/dev/null 2>&1; then
            # Sourcing also runs the script's own `complete` call, which registers it for the
            # compiler's name.  That is harmless -- it is a name this shell would otherwise
            # have no completion for -- and it is why this happens once per shell, not per TAB.
            # shellcheck disable=SC1090
            . "$script" >/dev/null 2>&1 || return 0
            declare -F "$fn" >/dev/null 2>&1 || return 0
          fi

          # The generated completer keys off argv[0] being the compiler's own name, which
          # here is `./flixw`.  Swap it for the length of the call and put it back: COMP_WORDS
          # belongs to the shell, not to us.
          saved0=${COMP_WORDS[0]}; saved_line=$COMP_LINE
          COMP_WORDS[0]=flix
          COMP_LINE="flix ${COMP_LINE#* }"
          "$fn"
          COMP_WORDS[0]=$saved0; COMP_LINE=$saved_line
          return 0
        }

        # Both spellings: nobody puts the wrapper on PATH, so `./flixw` is the form that
        # matters, and bash matches the command word as typed rather than resolving it.
        complete -F _flixw -o default flixw ./flixw
        """;

    static final String COMPL_ZSH = """
        #compdef flixw ./flixw
        # flixw TAB completion for zsh -- GENERATED by `flixw completion zsh`.
        #
        #   ./flixw completion zsh > "${fpath[1]}/_flixw"
        #
        # Candidates are read at TAB time from <project>/.flixw/local/verbs, the note stage 0
        # leaves after it resolves a compiler, so they follow the pin and this file does not
        # have to be regenerated after `pin`.  Nothing here starts a JVM.

        _flixw() {
          # The project is wherever the wrapper being completed lives, not the working
          # directory; :h on a bare name yields `.`, which is the same answer.
          local root=${words[1]:h}
          [[ -n $root ]] || root=.
          local note=$root/.flixw/local/verbs

          if (( CURRENT == 2 )); then
            local -a verbs
            # No note yet means no compiler has been resolved here; the baked-in list is this
            # release's own view, stale in the same harmless way stage 0's table is.
            if [[ -r $note ]]; then verbs=( ${(f)"$(<$note)"} )
            else verbs=( @VERBS@ ); fi
            _describe -t flixw-verbs 'flixw verb' verbs
            return
          fi

          # Past the verb the compiler owns the arguments.  picocli generates bash and zsh
          # completers as one bash script, which is not loadable here without bashcompinit
          # and a compatibility shim; rather than half-load it, fall through to files, which
          # is what the arguments to `run`, `check` and `build` mostly are.
          _files
        }

        _flixw "$@"
        """;

    static final String COMPL_FISH = """
        # flixw TAB completion for fish -- GENERATED by `flixw completion fish`.
        #
        #   ./flixw completion fish > ~/.config/fish/completions/flixw.fish
        #
        # Candidates are read at TAB time from <project>/.flixw/local/verbs, the note stage 0
        # leaves after it resolves a compiler, so they follow the pin and this file does not
        # have to be regenerated after `pin`.  Nothing here starts a JVM.
        #
        # Verbs only.  picocli generates bash and zsh completers and no fish one, and fish
        # cannot load a bash completion script, so past the verb fish's own file completion
        # takes over -- which is what the arguments to `run`, `check` and `build` mostly are.

        function __flixw_verbs --description 'the verbs the project being completed dispatches'
            set -l tokens (commandline -opc)
            test (count $tokens) -gt 0; or return
            # The project is wherever the wrapper being completed lives, not the working
            # directory: `../other/flixw` is a different project's verb set.  Done with
            # builtins rather than dirname, so a keypress costs no process at all.
            set -l root .
            if string match -q '*/*' -- $tokens[1]
                set root (string replace -r '/[^/]*$' '' -- $tokens[1])
                test -n "$root"; or set root /
            end
            set -l note $root/.flixw/local/verbs
            if test -r $note
                cat -- $note
            else
                # No note yet means this project has never resolved a compiler.  The baked-in
                # list is this wrapper release's own view -- stale in the same harmless way
                # the built-in verb table in stage 0 is, and better than completing nothing.
                printf '%s\\n' @VERBS@
            end
        end

        # fish matches on the command's base name, so this one registration covers `flixw`,
        # `./flixw` and an absolute path alike -- unlike bash, which matches the word as typed.
        complete -c flixw -f -n __fish_is_first_arg -a '(__flixw_verbs)'
        complete -c flixw -n 'not __fish_is_first_arg' -F
        """;

    static final String COMPL_PWSH = """
        # flixw TAB completion for PowerShell -- GENERATED by
        # `flixw completion pwsh`.
        #
        #   ./flixw completion pwsh >> $PROFILE
        #
        # Candidates are read at TAB time from <project>\\.flixw\\local\\verbs, the note stage 0
        # leaves after it resolves a compiler, so they follow the pin and this file does not
        # have to be regenerated after `pin`.  Nothing here starts a JVM.
        #
        # This registers against the existing flixw.cmd trampoline; PowerShell completes
        # native commands including batch files, so nothing has to move to a .ps1 -- and the
        # trampoline could not move anyway, since a .ps1 is not invokable as a bare command
        # from cmd.exe or from a build tool, and the default execution policy blocks a
        # downloaded one.  cmd.exe itself has no per-command completion mechanism at all, so
        # it gets nothing here and that is an absence in cmd, not a gap in this script.
        #
        # Verbs only.  picocli generates bash and zsh completers and no PowerShell one, so
        # past the verb there is nothing to delegate to and PowerShell's own file completion
        # takes over.
        Register-ArgumentCompleter -Native -CommandName flixw, flixw.cmd -ScriptBlock {
            param($wordToComplete, $commandAst, $cursorPosition)

            $elements = $commandAst.CommandElements
            # The verb position only; past it the compiler owns the arguments.
            if ($elements.Count -gt 2) { return }
            if ($elements.Count -eq 2 -and [string]::IsNullOrEmpty($wordToComplete)) { return }

            # The project is wherever the wrapper being completed lives, not the working
            # directory: another project's wrapper has another project's verb set.
            $root = Split-Path -Parent $elements[0].ToString()
            if ([string]::IsNullOrEmpty($root)) { $root = '.' }
            $note = Join-Path $root '.flixw/local/verbs'

            # No note yet means no compiler has been resolved here; the baked-in list is this
            # release's own view, stale in the same harmless way stage 0's table is.
            $verbs = if (Test-Path -LiteralPath $note) { Get-Content -LiteralPath $note }
                     else { @(@VERBS@) }

            $verbs | Where-Object { $_ -and $_.StartsWith($wordToComplete) } | ForEach-Object {
                [System.Management.Automation.CompletionResult]::new(
                    $_, $_, 'ParameterValue', $_)
            }
        }
        """;
}
